#!/usr/bin/env php
<?php
/**
 * @author: RunnerLee
 * @email: runnerleer@gmail.com
 * @time: 2017-08
 */

require __DIR__ . '/vendor/autoload.php';

use Dotenv\Dotenv;
use App\Vbot\Kernel;
use App\Vbot\MessageHandler\MissionMessageHandler;
use Swoole\Process;

/**
 * load environment config
 */
(new Dotenv(__DIR__, '.env'))->load();

$process = new Process(function () {

    /**
     * bootstrap vbot
     */
    $vbot = new Kernel(require __DIR__ . '/config/vbot.php');

    /**
     * load custom message handler
     */
    $vbot->messageExtension->load([
        MissionMessageHandler::class,
    ]);

    /**
     * start server
     */
    $vbot->server->serve();

});

$process->daemon();

$process->start();