#!/usr/bin/env php
<?php
/**
 * @author: RunnerLee
 * @email: runnerleer@gmail.com
 * @time: 2017-08
 */

require __DIR__ . '/vendor/autoload.php';

use Dotenv\Dotenv;
use App\Vbot\Kernel;
use App\Vbot\MessageHandler\MissionMessageHandler;
use Swoole\Process;

/**
 * load environment config
 */
(new Dotenv(__DIR__, '.env'))->load();

/**
 * bootstrap vbot
 */
$vbot = new Kernel(require __DIR__ . '/config/vbot.php');


$vbot->observer->setQrCodeObserver(function ($url) {
    file_put_contents(vbot()['config']['path'] . '/url.txt', $url);
});

/**
 * load custom message handler
 */
$vbot->messageExtension->load([
    MissionMessageHandler::class,
]);

/**
 * load custom message handler
 */
$vbot->messageExtension->load([
    MissionMessageHandler::class,
]);

/**
 * start server
 */
$vbot->server->serve();